version: '3.8'

services:
  webstack:
    image: dockeruserstlara/webstackhugo:latest
    container_name: webstack-hugo
    restart: always
    ports:
      - "8080:80"
    volumes:
      - /opt/webstackhugo/config:/config:ro
      - /opt/webstackhugo/data/exampleSite:/data/exampleSite:ro
      - /opt/webstackhugo/data/layouts:/data/layouts:ro
      - /opt/webstackhugo/data/static:/data/static:ro
